name: Generate Labs on Template Update

on:
  push:
    paths:
      - 'Labsible/IOTC/IOTC_Labs/templates/**'

jobs:
  generate-labs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Show directory structure (debugging)
      run: |
        pwd
        ls -la
        find . -type d

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd Labsible/IOTC/IOTC_Labs
        python -m pip install --upgrade pip
        pip install jinja2 pyyaml

    - name: Run lab generation script
      run: |
        cd Labsible/IOTC/IOTC_Labs
        python generate_labs.py

    - name: Commit and push generated output files
      run: |
        cd Labsible/IOTC/IOTC_Labs/output
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Auto-commit generated lab files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

